"""Create StockData table

Revision ID: 05fc8ca797ee
Revises: 
Create Date: 2025-01-18 09:40:24.621934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import os
import csv


# revision identifiers, used by Alembic.
revision: str = '05fc8ca797ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    stock_data_table = op.create_table('stock_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('daily_pct_change', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_data_date'), 'stock_data', ['date'], unique=False)
    # ### end Alembic commands ###
    csv_file_path = os.path.join(os.path.dirname(__file__), '../bootstrap/snp500prices.csv')

    # Open and read the CSV file
    with open(csv_file_path, 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        # Prepare the data for insertion
        rows = [
            {
                'date': row['Date'],
                'price': float(row['price']),
                'ticker': row['ticker'],
                'daily_pct_change': float(row['daily_pct_change']),
            }
            for row in reader
        ]
    
    # Insert the data into the table
    op.bulk_insert(stock_data_table, rows)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_data_date'), table_name='stock_data')
    op.drop_table('stock_data')
    # ### end Alembic commands ###
