"""Industry Data Index

Revision ID: 2366aebbf8a8
Revises: e680382ea850
Create Date: 2025-01-20 17:24:22.083875

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2366aebbf8a8"
down_revision: Union[str, None] = "e680382ea850"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_industry_data_symbol"), "industry_data", ["symbol"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_industry_data_symbol"), table_name="industry_data")
    # ### end Alembic commands ###
