"""Index StockData table

Revision ID: 9d1f41ae963e
Revises: f43302b0ae38
Create Date: 2025-01-18 17:30:01.932832

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d1f41ae963e"
down_revision: Union[str, None] = "f43302b0ae38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_stock_data_date"), "stock_data", ["date"], unique=False)
    op.create_index(
        op.f("ix_stock_data_ticker"), "stock_data", ["ticker"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_data_ticker"), table_name="stock_data")
    op.drop_index(op.f("ix_stock_data_date"), table_name="stock_data")
    # ### end Alembic commands ###
