"""Industry Data

Revision ID: e680382ea850
Revises: d6e701e7f6d7
Create Date: 2025-01-20 14:31:35.400769

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e680382ea850"
down_revision: Union[str, None] = "d6e701e7f6d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    industry_data_table = op.create_table(
        "industry_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("last_sale", sa.String(length=10), nullable=True),
        sa.Column("market_cap", sa.String(length=10), nullable=True),
        sa.Column("ipo_year", sa.String(length=10), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=150), nullable=True),
        sa.Column("summary_quote", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_industry_data_id"), "industry_data", ["id"], unique=False)
    # ### end Alembic commands ###
    from sqlalchemy.orm import Session

    from db import industry_data_hook

    connection = op.get_bind()
    session = Session(bind=connection)
    industry_data_hook(session, industry_data_table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_industry_data_id"), table_name="industry_data")
    op.drop_table("industry_data")
    # ### end Alembic commands ###
